### ISSUE TITLE
Terminates after a short time with 'blocks Buffer full'

### ISSUE THREAD

**Issue by bminish** [fventuri/dual-tuner-recorder#2]
I'm running on Fedora Linux (ver 42) and have been using linrad to make hours long recordings of both receivers covering the MW broadcast band.

However dual_tuner_recorder is terminating after a short period with 'blocks buffer full'. 

The sdrplay Duo is remotely located, connected to a Raspberry Pi4 and the USB port is exported via USBIP to my 64 bit Fedora Linux desktop, both SDRconnect and Linrad are able to run stability with this setup but USB latencies will be much higher than a real, physical & local USB port.
Perhaps the issue is one of having deep enough buffers (& one could probably use  'very deep' buffering for a recording application such as this)  ?  

Also shouldn't both tuners be showing the same settings here ? 

bminish@redbox:~/Radio/01-IQ-files$ dual_tuner_recorder -r 6000000 -i 1620 -b 1536 -l 1 -f 990000 -L -v -X 99 -G -x 7200
SerNo=2403011F34 hwVer=3 tuner=0x03 rspDuoMode=0x02 rspDuoSampleFreq=6000000 internalDecimation=3
RX A - LO=990000 BW=1536 If=1620 Dec=1 IFagc=0 IFgain=40 LNAgain=1
RX A - DCenable=1 IQenable=1 dcCal=3 speedUp=0 trackTime=1 refreshRateTime=2048
RX B - LO=200000000 BW=200 If=1620 Dec=1 IFagc=2 IFgain=50 LNAgain=0
RX B - DCenable=1 IQenable=1 dcCal=3 speedUp=0 trackTime=1 refreshRateTime=2048
streaming for 7200 seconds
blocks buffer full
total samples = 400733172 / 400732920
elapsed time = 200.359120 / 200.359065
actual sample rate = 2000075 / 2000074
I samples range = [-18600,18415] / [-20543,21022]
Q samples range = [-19312,19491] / [-20439,20471]
samples per rx_callback range = [252,252] / [252,252]
output samples = 400720572 (x2)
data size = 3205764576

bminish@redbox:~/Radio/01-IQ-files$ cd /home/linrad_data/
bminish@redbox:/home/linrad_data$ dual_tuner_recorder -r 6000000 -i 1620 -b 1536 -l 1 -f 990000 -L -v -X 99 -G -x 7200
SerNo=2403011F34 hwVer=3 tuner=0x03 rspDuoMode=0x02 rspDuoSampleFreq=6000000 internalDecimation=3
RX A - LO=990000 BW=1536 If=1620 Dec=1 IFagc=0 IFgain=40 LNAgain=1
RX A - DCenable=1 IQenable=1 dcCal=3 speedUp=0 trackTime=1 refreshRateTime=2048
RX B - LO=200000000 BW=200 If=1620 Dec=1 IFagc=2 IFgain=50 LNAgain=0
RX B - DCenable=1 IQenable=1 dcCal=3 speedUp=0 trackTime=1 refreshRateTime=2048
streaming for 7200 seconds
blocks buffer full
total samples = 61170228 / 61169976
elapsed time = 30.591592 / 30.591554
actual sample rate = 1999576 / 1999571
I samples range = [-17513,17297] / [-20594,19977]
Q samples range = [-17975,17818] / [-20980,19935]
samples per rx_callback range = [252,252] / [252,252]
output samples = 61157628 (x2)
data size = 489261024
gain changes = 0 / 0
bminish@redbox:/home/linrad_data$ time dual_tuner_recorder -r 6000000 -i 1620 -b 1536 -l 1 -f 990000 -L -v -X 99 -G -x 7200
SerNo=2403011F34 hwVer=3 tuner=0x03 rspDuoMode=0x02 rspDuoSampleFreq=6000000 internalDecimation=3
RX A - LO=990000 BW=1536 If=1620 Dec=1 IFagc=0 IFgain=40 LNAgain=1
RX A - DCenable=1 IQenable=1 dcCal=3 speedUp=0 trackTime=1 refreshRateTime=2048
RX B - LO=200000000 BW=200 If=1620 Dec=1 IFagc=2 IFgain=50 LNAgain=0
RX B - DCenable=1 IQenable=1 dcCal=3 speedUp=0 trackTime=1 refreshRateTime=2048
streaming for 7200 seconds
blocks buffer full
total samples = 39567780 / 39567528
elapsed time = 19.776615 / 19.776542
actual sample rate = 2000736 / 2000730
I samples range = [-16613,17657] / [-19832,19826]
Q samples range = [-17537,17867] / [-19624,19904]
samples per rx_callback range = [252,252] / [252,252]
output samples = 39555180 (x2)
data size = 316441440
gain changes = 0 / 0

real    0m21.562s
user    0m1.401s
sys     0m2.894s

**Comment by fventuri** [comment]
@bminish - thanks for reporting the problems.

I agree with your idea of increasing the buffer size - I just changed it from 64k samples to 1M samples, run a test for 10 minutes with the command below, and it completes successfully without the `blocks buffer full` error.
I also removed -the `-X` option because that flag enables debugging in the SDRplay API, which introduces some (significant?) overhead.

This the command I just ran here for my 10 minutes test:
```
time dual_tuner_recorder -r 6000000 -i 1620 -b 1536 -l 1 -f 990000 -L -v -x 600 -o '/tmp/RSPduo_dual_tuner_{TIMESTAMP}_{FREQKHZ}.raw'
```

I also fixed the problem with the settings of tuner B not being printed correctly - now the displayed values for both tuners should be consistent.

Please run `git pull` to get the latest code, rebuild `dual_tuner_recorder`, and let me know if it works for you too.

Franco

**Comment by bminish** [comment]
Hi Franco,

That seems to be quite a bit more stable and I was able to make a 10 minute recording with no errors, which then imports correctly into wavviewdx with full diversity. This is great & finally a way to make diversity recordings I can control with cron files.

However I still ran into issues with a longer recording, this time with samples being dropped (see below) 

to give you an idea of just how 'horrible' the latencies are (in USB terms!) here's a bunch of pings (  10 per sec) sent across the path to the USBIP host where the rspDuo is connected.  at the time the link was also carrying 200  -- 400 Mbs of traffic too, the duo is in full diversity ~200M
this is a 5Ghz 802.11ax connection.
It is well optimised point to point link, but USB terms, a RTT of 18 msec +  must be a very long time! 

Happy to gather any additional metrics that may be helpful in terms of debugging 

--- remrx ping statistics ---
5313 packets transmitted, 5313 received, 0% packet loss, time 534471ms
rtt min/avg/max/mdev = 1.915/4.338/18.194/1.231 ms
bminish@redbox:~$ 


bminish@redbox:/home/linrad_data$ time dual_tuner_recorder -r 6000000 -i 1620 -b 1536 -l 0 -f 990000 -L -v -x 7200
SerNo=2403011F34 hwVer=3 tuner=0x03 rspDuoMode=0x02 rspDuoSampleFreq=6000000 internalDecimation=3
RX A - LO=990000 BW=1536 If=1620 Dec=1 IFagc=0 IFgain=40 LNAgain=0
RX A - DCenable=1 IQenable=1 dcCal=3 speedUp=0 trackTime=1 refreshRateTime=2048
RX B - LO=990000 BW=1536 If=1620 Dec=1 IFagc=0 IFgain=40 LNAgain=0
RX B - DCenable=1 IQenable=1 dcCal=3 speedUp=0 trackTime=1 refreshRateTime=2048
streaming for 7200 seconds
RX A - dropped 7347 samples
RX B - dropped 7347 samples
dropped 7347 samples - next_sample_num=1152218676 first_sample_num=1152226023
RX A - dropped 2887 samples
RX B - dropped 2887 samples
dropped 2887 samples - next_sample_num=1265665839 first_sample_num=1265668726
RX A - dropped 4454 samples
RX B - dropped 4454 samples

<... snip... > (needed a Ctrl C to exit) 

dropped 5025 samples - next_sample_num=178307101 first_sample_num=178312126
RX A - dropped 3928 samples
RX B - dropped 3928 samples
dropped 3928 samples - next_sample_num=182969086 first_sample_num=182973014

^Ctotal samples = 1618735104 / 1618735104
elapsed time = 809.553443 / 809.553426
actual sample rate = 1999541 / 1999541
I samples range = [-20265,21612] / [-21521,21594]
Q samples range = [-20788,20463] / [-21638,22161]
samples per rx_callback range = [252,252] / [252,252]
output samples = 1618735104 (x2)
data size = 12949880832
gain changes = 0 / 0

real    13m31.231s
user    0m30.650s
sys     1m2.673s

**Comment by fventuri** [comment]
Thanks for your tests.

I just added a few lines of code to print the blocks buffer and samples buffer usage at the end.
I just ran it for 10 minutes here (in my case the USB connection to the RSPduo is direct), and my output statistics show the following (the values displayed are max_used/capacity):
```
blocks buffer usage = 56/1000
samples buffer usage = 28224/1048576
```
in order words in my case both buffers are hardly used.

I would be interested to see your statistics since your setup is kind of unusual.

I also added a couple of command line options:
- `-j` to select the blocks buffer size (default: 1000)
- `-k` to select the samples buffer size (default: 1048576)

If you have time, please try to run a few tests changing those settings, and let me know your findings.

Franco

**Comment by fventuri** [comment]
This morning I read your last message paying more attention, and I noticed that in some cases the number of dropped samples is an odd number (7347, 2887). I didn't expect that, since I assumed the number of dropped samples was always an integer multiple of the callback sample size (252 samples for the RSPduo sampling at 2Msps), but apparently this is not the case.

In the statistics print at the end of the run I added the total number of dropped samples, and I also fixed a couple of bugs I had yesterday when I added those `-j` and `-k` command line parameters to set the blocks and samples buffer sizes.

If you run more tests today or in the next few days, please use the latest code from GitHub.

Franco

**Comment by bminish** [comment]
NOTE! Please disregard as all pre dates your last change, now re-running some tests and will report later  ;-) 



This run ended prematurely after 12G written with 'blocks buffers full' (underlying storage is NVME, dedicated at the moment for RF capture. ) 

time dual_tuner_recorder -r 6000000 -i 1620 -b 1536 -g AGC -G -l 1 -f 990000 -L -v -x 3600


blocks buffer full
total samples = 1537866540 / 1537866288
elapsed time = 768.899749 / 768.899673
actual sample rate = 2000087 / 2000087
I samples range = [-3041,3235] / [-3619,3587]
Q samples range = [-3144,3078] / [-3527,3547]
samples per rx_callback range = [252,252] / [252,252]
output samples = 1537740540 (x2)
data size = 12301924320
blocks buffer usage = 1000/1000
samples buffer usage = 504504/1048576
gain changes = 5 / 5

real    12m50.741s
user    0m54.089s
sys     2m1.588s

Second run, 4x the block buffer size (but did it apply this, seems that the new flags are ignored ? )

bminish@redbox:/home/linrad_data$ time dual_tuner_recorder -r 6000000 -i 1620 -b 1536 -g AGC -G -l 1 -f 990000 -L -v -x 3600 -j 4000
SerNo=2403011F34 hwVer=3 tuner=0x03 rspDuoMode=0x02 rspDuoSampleFreq=6000000 internalDecimation=3
RX A - LO=990000 BW=1536 If=1620 Dec=1 IFagc=2 IFgain=50 LNAgain=1
RX A - DCenable=1 IQenable=1 dcCal=3 speedUp=0 trackTime=1 refreshRateTime=2048
RX B - LO=990000 BW=1536 If=1620 Dec=1 IFagc=2 IFgain=50 LNAgain=1
RX B - DCenable=1 IQenable=1 dcCal=3 speedUp=0 trackTime=1 refreshRateTime=2048
streaming for 3600 seconds
blocks buffer full
total samples = 1340234028 / 1340233776
elapsed time = 670.021756 / 670.021695
actual sample rate = 2000284 / 2000284
I samples range = [-5665,4780] / [-3452,3698]
Q samples range = [-5745,4982] / [-4209,3834]
samples per rx_callback range = [252,252] / [252,252]
output samples = 1340108028 (x2)
data size = 10720864224
blocks buffer usage = 1000/1000
samples buffer usage = 504504/1048576
gain changes = 5 / 5

real    11m11.689s
user    0m43.708s
sys     1m40.245s

Edited the source code to increase the block buffer size to 4000 (line 27 #define NUM_BLOCKS 4000 ) 
and reran  
time dual_tuner_recorder -r 6000000 -i 1620 -b 1536 -g AGC -G -l 1 -f 990000 -L -v -x 3600 -j 4000


this run is strange! we dropped some samples, did complete the run but filled neither buffer 

bminish@redbox:/home/linrad_data$ time dual_tuner_recorder -r 6000000 -i 1620 -b 1536 -g AGC -G -l 1 -f 990000 -L -v -x 3600 -j 4000
SerNo=2403011F34 hwVer=3 tuner=0x03 rspDuoMode=0x02 rspDuoSampleFreq=6000000 internalDecimation=3
RX A - LO=990000 BW=1536 If=1620 Dec=1 IFagc=2 IFgain=50 LNAgain=1
RX A - DCenable=1 IQenable=1 dcCal=3 speedUp=0 trackTime=1 refreshRateTime=2048
RX B - LO=990000 BW=1536 If=1620 Dec=1 IFagc=2 IFgain=50 LNAgain=1
RX B - DCenable=1 IQenable=1 dcCal=3 speedUp=0 trackTime=1 refreshRateTime=2048
streaming for 3600 seconds
RX A - dropped 1431655765 samples
RX B - dropped 1431655765 samples
dropped 1431655765 samples - next_sample_num=1431655932 first_sample_num=167
RX A - dropped 1431655765 samples
RX B - dropped 1431655765 samples
dropped 1431655765 samples - next_sample_num=1431656015 first_sample_num=250
RX A - dropped 1431655766 samples
RX B - dropped 1431655766 samples
dropped 1431655766 samples - next_sample_num=1431655846 first_sample_num=80
RX A - dropped 1431655765 samples
RX B - dropped 1431655765 samples
dropped 1431655765 samples - next_sample_num=1431655928 first_sample_num=163
RX A - dropped 1431655765 samples
RX B - dropped 1431655765 samples
dropped 1431655765 samples - next_sample_num=1431656011 first_sample_num=246
total samples = 7199958528 / 7199958528
elapsed time = 3599.912206 / 3599.912192
actual sample rate = 2000037 / 2000037
I samples range = [-19608,20263] / [-17577,16520]
Q samples range = [-19148,20633] / [-18121,18171]
samples per rx_callback range = [252,252] / [252,252]
output samples = 7199958528 (x2)
data size = 57599668224
blocks buffer usage = 512/4000
samples buffer usage = 258048/1048576
gain changes = 5 / 5

real    60m1.650s
user    3m38.901s
sys     8m1.657s


Modified the code again to further increase buffers (lines 27/28) 
#define NUM_BLOCKS 16000
#define NUM_SAMPLES 4194304

Another run 
time dual_tuner_recorder -r 6000000 -i 1620 -b 1536 -g AGC -G -l 1 -f 990000 -L -v -x 7200 -j 16000 -k 4194304

**Comment by bminish** [comment]
Ok, with the latest version I am still seeing some errors so I tried even bigger blocks & buffers, however these do not appear to have been fully utilized (see below!)  

time dual_tuner_recorder -r 6000000 -i 1620 -b 1536 -g AGC -G -l 1 -f 990000 -L -v -j 4000 -k 4194304 -x 3600

I ended this run with Ctrl C  and truncated some 'dropped samples' messages as they went beyond my console buffer
I was also watching the system log for messages from the sdrplay API and I note 2 things 

1/ each session starts with an error 
2/ at the onset of the dropped samples errors we see libusb errors (& I note that linrad uses bulk transfers not iso ones , if this may also relax timing ? ) 

May 13 17:17:43 redbox sdrplay_apiService[82732]: [82924]: devIdx0: sdrplay_apiService_rsp: rspDuoTuner1AmNotchEnable: ERROR: Wrong tuner 3
May 13 17:38:37 redbox sdrplay_apiService[82732]: libusb: error [submit_iso_transfer] submiturb failed, errno=12
May 13 17:46:55 redbox sdrplay_apiService[82732]: libusb: error [submit_iso_transfer] submiturb failed, errno=12
May 13 17:46:55 redbox sdrplay_apiService[82732]: libusb: error [submit_iso_transfer] submiturb failed, errno=12
May 13 17:46:55 redbox sdrplay_apiService[82732]: libusb: error [submit_iso_transfer] submiturb failed, errno=12
May 13 17:47:07 redbox sdrplay_apiService[82732]: libusb: error [submit_iso_transfer] submiturb failed, errno=12
May 13 17:47:09 redbox sdrplay_apiService[82732]: libusb: error [submit_iso_transfer] submiturb failed, errno=12
May 13 17:48:53 redbox sdrplay_apiService[82732]: [82732]: sdrplay_apiService: ReleaseDevice: MSG: Releasing 2403011F34
May 13 17:48:53 redbox sdrplay_apiService[82732]: [82926]: sdrplay_apiService_rsp: streamThread: Exit
May 13 17:48:53 redbox sdrplay_apiService[82732]: [82924]: sdrplay_apiService_device: mCmdHandlerThread: Exit
May 13 17:48:53 redbox sdrplay_apiService[82732]: [82925]: sdrplay_apiService_device: sCmdHandlerThread: Exit



RX A - dropped 2999 samples
RX B - dropped 2999 samples
dropped 2999 samples - next_sample_num=811044163 first_sample_num=811047162
RX A - dropped 5255 samples
RX B - dropped 5255 samples
dropped 5255 samples - next_sample_num=811527474 first_sample_num=811532729
RX A - dropped 2753 samples
RX B - dropped 2753 samples
dropped 2753 samples - next_sample_num=811660997 first_sample_num=811663750
RX A - dropped 6749 samples
RX B - dropped 6749 samples
dropped 6749 samples - next_sample_num=811728010 first_sample_num=811734759
RX A - dropped 1877 samples
RX B - dropped 1877 samples
dropped 1877 samples - next_sample_num=812135187 first_sample_num=812137064
RX A - dropped 10252 samples
RX B - dropped 10252 samples
dropped 10252 samples - next_sample_num=812233328 first_sample_num=812243580
RX A - dropped 1998 samples
RX B - dropped 1998 samples
dropped 1998 samples - next_sample_num=812275836 first_sample_num=812277834
RX A - dropped 3749 samples
RX B - dropped 3749 samples
dropped 3749 samples - next_sample_num=812438106 first_sample_num=812441855
RX A - dropped 2000 samples
RX B - dropped 2000 samples
dropped 2000 samples - next_sample_num=812474111 first_sample_num=812476111
RX A - dropped 2376 samples
RX B - dropped 2376 samples
dropped 2376 samples - next_sample_num=812716519 first_sample_num=812718895
RX A - dropped 4000 samples
RX B - dropped 4000 samples
dropped 4000 samples - next_sample_num=812783155 first_sample_num=812787155
RX A - dropped 5500 samples
RX B - dropped 5500 samples
dropped 5500 samples - next_sample_num=812883419 first_sample_num=812888919
RX A - dropped 4499 samples
RX B - dropped 4499 samples



^Ctotal samples = 3730954752 / 3730954752
dropped samples = 2869717282 / 2869717282
elapsed time = 1868.615467 / 1868.615458
actual sample rate = 1996641 / 1996641
I samples range = [-20904,20435] / [-18057,20662]
Q samples range = [-20154,20054] / [-18504,19519]
samples per rx_callback range = [252,252] / [252,252]
output samples = 3730954752 (x2)
data size = 29847638016
blocks buffer usage = 512/4000
samples buffer usage = 258048/4194304
gain changes = 6 / 6

real    31m10.338s
user    1m47.365s
sys     4m3.269s


May 13 17:38:37 redbox sdrplay_apiService[82732]: libusb: error [submit_iso_transfer] submiturb failed, errno=12
May 13 17:46:55 redbox sdrplay_apiService[82732]: libusb: error [submit_iso_transfer] submiturb failed, errno=12
May 13 17:46:55 redbox sdrplay_apiService[82732]: libusb: error [submit_iso_transfer] submiturb failed, errno=12
May 13 17:46:55 redbox sdrplay_apiService[82732]: libusb: error [submit_iso_transfer] submiturb failed, errno=12
May 13 17:47:07 redbox sdrplay_apiService[82732]: libusb: error [submit_iso_transfer] submiturb failed, errno=12
May 13 17:47:09 redbox sdrplay_apiService[82732]: libusb: error [submit_iso_transfer] submiturb failed, errno=12

**Comment by bminish** [comment]
I've altered the code at line 430 to switch to bulk mode and I am seeing far fewer issues, in my use case at least. and the API no longer logs  libusb errors .


added at line 430 

    /**
     Set the mode to sdrplay_api_ISOCH or sdrplay_api_BULK
    The default if unspecififed is sdrplay_api_ISOCH
    device_params->devParams->mode = sdrplay_api_ISOCH;
    **/
    device_params->devParams->mode = sdrplay_api_BULK;

**Comment by fventuri** [comment]
@bminish - thanks for your suggestion about using USB bulk mode; I remember reading that USB bulk mode can provide more throughput than USB isochronous mode, so that would explain why you see way less dropped packets.

However this morning when I added that line to switch to USB bulk mode, and then I ran it with the same command line arguments, the call to `sdrplay_api_Init` failed. The logs show this error messages:
```
May 14 08:25:09 fvdesktop sdrplay_apiService[2226]: [2341]: devIdx0: sdrplay_apiService_rsp: usb_ControlTransfer: Error: libusb_control_transfer() -7
May 14 08:25:09 fvdesktop sdrplay_apiService[2226]: [2341]: devIdx0: sdrplay_apiService_rsp: bridge_StartRx: bridge_StartRx: Transfer failed
May 14 08:25:09 fvdesktop sdrplay_apiService[2226]: [2341]: devIdx0: sdrplay_apiService_rsp: initHw: Tuner3: initHw: bridge_StartRx() Error 0x00000001
May 14 08:25:09 fvdesktop sdrplay_apiService[2226]: [2341]: devIdx0: sdrplay_apiService_rsp: Init: ERROR: Tuner3: initHw returned error 7
```

I am not really sure what exactly is going on and why, but I'll try to spend more time on this tonight after work.

Franco

**Comment by bminish** [comment]
This might look bad as in there are still some dropped samples, but:
1/ the files now play ok, I just about hear the drop sometimes, but everything including phase relationship between both Receivers remains intact, buffer usage is modest and recordings complete their full duration.  
2/ we are now down to these drops occurring infrequently & seemingly coinciding with short CPU load or I/O spikes on my host machine, every ~ 15 min, which I suspect are something blocking / preturbing the usbip driver part of the connection since presumably this is a rather timing sensitive ;-)
 It's a pity there's not a good way to have the sdrplay API it's self handle client /server mode over tcp/ip ..


I did run into a few instances when I was playing with very small buffers etc, where I could cause it to leave the rspDuo in some sort of stuck state, requiring me to run sdrconnect, then exit that to get the duo back into a suitable state where 'dual-tuner could successfully connect to it again. Perhaps there's a reset or initialisation required if the RX has been left 'hanging' ?

bminish@redbox:/home/linrad_data$ time dual_tuner_recorder -r 6000000 -i 1620 -b 1536 -g AGC -l 1 -G -f 990000 -L -j 4000 -v -x 7200
SerNo=2403011F34 hwVer=3 tuner=0x03 rspDuoMode=0x02 rspDuoSampleFreq=6000000 internalDecimation=3
RX A - LO=990000 BW=1536 If=1620 Dec=1 IFagc=2 IFgain=50 LNAgain=1
RX A - DCenable=1 IQenable=1 dcCal=3 speedUp=0 trackTime=1 refreshRateTime=2048
RX B - LO=990000 BW=1536 If=1620 Dec=1 IFagc=2 IFgain=50 LNAgain=1
RX B - DCenable=1 IQenable=1 dcCal=3 speedUp=0 trackTime=1 refreshRateTime=2048
streaming for 7200 seconds
RX A - dropped 1431655765 samples
RX B - dropped 1431655765 samples
dropped 1431655765 samples - next_sample_num=1431655932 first_sample_num=167
RX A - dropped 1431655765 samples
RX B - dropped 1431655765 samples
dropped 1431655765 samples - next_sample_num=1431656015 first_sample_num=250
RX A - dropped 1431655766 samples
RX B - dropped 1431655766 samples
dropped 1431655766 samples - next_sample_num=1431655846 first_sample_num=80
RX A - dropped 1431655765 samples
RX B - dropped 1431655765 samples
dropped 1431655765 samples - next_sample_num=1431655928 first_sample_num=163
RX A - dropped 1431655765 samples
RX B - dropped 1431655765 samples
dropped 1431655765 samples - next_sample_num=1431656011 first_sample_num=246
RX A - dropped 1431655766 samples
RX B - dropped 1431655766 samples
dropped 1431655766 samples - next_sample_num=1431655842 first_sample_num=76
RX A - dropped 1431655765 samples
RX B - dropped 1431655765 samples
dropped 1431655765 samples - next_sample_num=1431655924 first_sample_num=159
RX A - dropped 12178 samples
RX B - dropped 12178 samples
dropped 12178 samples - next_sample_num=1350150639 first_sample_num=1350162817
RX A - dropped 1431655765 samples
RX B - dropped 1431655765 samples
dropped 1431655765 samples - next_sample_num=1431655837 first_sample_num=72
RX A - dropped 8656 samples
RX B - dropped 8656 samples
dropped 8656 samples - next_sample_num=1339367724 first_sample_num=1339376380
RX A - dropped 1431655766 samples
RX B - dropped 1431655766 samples
dropped 1431655766 samples - next_sample_num=1431656008 first_sample_num=242
RX A - dropped 1431655765 samples
RX B - dropped 1431655765 samples
dropped 1431655765 samples - next_sample_num=1431655838 first_sample_num=73
total samples = 14399949312 / 14399949312
dropped samples = 14316578487 / 14316578487
elapsed time = 7199.889881 / 7199.889873
actual sample rate = 2000024 / 2000024
I samples range = [-16168,15091] / [-10426,10555]
Q samples range = [-18123,13679] / [-9753,9391]
samples per rx_callback range = [252,252] / [252,252]
output samples = 14399949312 (x2)
data size = 115199594496
blocks buffer usage = 512/4000
samples buffer usage = 258048/1048576
gain changes = 7 / 6

real    120m1.786s
user    5m26.547s
sys     13m4.470s

I modified the code as follows (comment block & line to set bulk mode)

`// select device settings
    sdrplay_api_DeviceParamsT *device_params;
    err = sdrplay_api_GetDeviceParams(device.dev, &device_params);
    if (err != sdrplay_api_Success) {
        fprintf(stderr, "sdrplay_api_GetDeviceParams() failed: %s\n", sdrplay_api_GetErrorString(err));
        sdrplay_api_ReleaseDevice(&device);
        sdrplay_api_Close();
        exit(1);
    }
    sdrplay_api_RxChannelParamsT *rx_channelA_params = device_params->rxChannelA ;
    sdrplay_api_RxChannelParamsT *rx_channelB_params = device_params->rxChannelB ;
    device_params->devParams->fsFreq.fsHz = rspduo_sample_rate;
    /**
     Set the mode to sdrplay_api_ISOCH or sdrplay_api_BULK
    The default if unspecififed is sdrplay_api_ISOCH
    device_params->devParams->mode = sdrplay_api_ISOCH;
    **/
    device_params->devParams->mode = sdrplay_api_BULK;
    rx_channelA_params->ctrlParams.decimation.enable = decimation > 1;
    rx_channelA_params->ctrlParams.decimation.decimationFactor = decimation;
    rx_channelA_params->rspDuoTunerParams.tuner1AmPortSel = sdrplay_api_RspDuo_AMPORT_2;
    rx_channelA_params->tunerParams.ifType = if_frequency;
    rx_channelA_params->tunerParams.bwType = if_bandwidth;
    rx_channelA_params->ctrlParams.agc.enable = agc_A;
    if (agc_A == sdrplay_api_AGC_DISABLE) {
        rx_channelA_params->tunerParams.gain.gRdB = gRdB_A;
    }
    rx_channelA_params->tunerParams.gain.LNAstate = LNAstate_A;
    rx_channelA_params->ctrlParams.dcOffset.DCenable = DCenable;
    rx_channelA_params->ctrlParams.dcOffset.IQenable = IQenable;
    rx_channelB_params->ctrlParams.decimation.enable = decimation > 1;
    rx_channelB_params->ctrlParams.decimation.decimationFactor = decimation;
    rx_channelB_params->tunerParams.ifType = if_frequency;
    rx_channelB_params->tunerParams.bwType = if_bandwidth;
    rx_channelB_params->ctrlParams.agc.enable = agc_B;
    if (agc_B == sdrplay_api_AGC_DISABLE) {
        rx_channelA_params->tunerParams.gain.gRdB = gRdB_B;
    }
    rx_channelB_params->tunerParams.gain.LNAstate = LNAstate_B;
    rx_channelB_params->ctrlParams.dcOffset.DCenable = DCenable;
    rx_channelB_params->ctrlParams.dcOffset.IQenable = IQenable;
    rx_channelA_params->tunerParams.dcOffsetTuner.dcCal = dcCal;
    rx_channelA_params->tunerParams.dcOffsetTuner.speedUp = speedUp;
    rx_channelA_params->tunerParams.dcOffsetTuner.trackTime = trackTime;
    rx_channelA_params->tunerParams.dcOffsetTuner.refreshRateTime = refreshRateTime;
    rx_channelB_params->tunerParams.dcOffsetTuner.dcCal = dcCal;
    rx_channelB_params->tunerParams.dcOffsetTuner.speedUp = speedUp;
    rx_channelB_params->tunerParams.dcOffsetTuner.trackTime = trackTime;
    rx_channelB_params->tunerParams.dcOffsetTuner.refreshRateTime = refreshRateTime;
    rx_channelA_params->tunerParams.rfFreq.rfHz = frequency_A;
    rx_channelB_params->tunerParams.rfFreq.rfHz = frequency_B;

    int internal_decimation = get_internal_decimation(device_params, device.rspDuoSampleFreq);
    if (internal_decimation == -1) {
        fprintf(stderr, "invalid dual tuner settings - check sample rate, IF bandwidth, and IF frequency\n");
        sdrplay_api_ReleaseDevice(&device);
        sdrplay_api_Close();
        exit(1);
    }`

**Comment by fventuri** [comment]
I strongly suspect that those cases with a very high number of dropped samples are not real, and are very likely an artifact of either the SDRplay API or USBIP.
The reason I am saying this is because the hexadecimal representation of number of dropped samples (1431655765) is 0x55555555; in binary it is 1010101010101010101010101010101

Franco

**Comment by bminish** [comment]
That's an interesting observation & makes sense, 1431655765 samples is a big hole in the data, even at 4M (2x 2M streams)   which I should be able to hear easily & would lead to notecable timeslip across a 2 Hour file whereas 12178 or 8656 lost is just a glitch that the noise blanker (& the oceans of band noise that is MW Dxing )  in wavviewdx swallows and I'm not going to notice ~5 msec time slip (~20,000 samples /2 dropped total)  across 2 hours . 
I'll have a think about how I might rule USBIP out of the equation here. 

I can confirm I am using the latest version of the API from sdrplay's website 

Thank you for your work on this, I'm now making long captures with few issues and with software that is easy to schedule.

**Comment by fventuri** [comment]
I came up with a theory that might explain that very odd value for the gap in sample sequence.

I noticed that `1431655765 = (2^32 - 1) / 3`, and 3 is the internal decimation factor selected by the SDRplay API when the RSPduo sample rate is 6MHz, and the IF frequency is 1620kHz, which are the settings you have in your tests.
So what I think it is happening is that there's another sample counter somewhere in the SDRplay API before the internal decimation by 3; that counter is stored as a 32 bit unsigned variable, and that variable wraps around from 2^32 -1 (0xffffffff) to 0 (0x00000000), but because of the internal decimation by 3, the SDRplay API returns a skip of (2^32 - 1) / 3 sample numbers in their sequence.

If my theory is correct, we should see a similar behavior in the configuration with the RSPduo sample rate set to 8,000,000, the IF frequency = 2048kHz, and the IF bandwidth = 2048kHz (this is the second row in the table in this section: https://github.com/fventuri/dual-tuner-recorder#important-note-about-sample-rates-if-frequency-and-if-bandwidth-when-operating-the-rspduo-in-dual-tuner-mode).
However in this case the internal decimation factor is 4, so I would expect the gap in sequence numbers to be 1073741823 or 1073741824, which is  (2^32 - 1) / 4

To confirm my theory, I thought you could run another of your test recordings with these settings:
```
time dual_tuner_recorder -r 8000000 -i 2048 -b 1536 -g AGC -l 1 -G -f 990000 -L -j 4000 -v -x 7200
```
I am very interested in seeing what the results are in this case.

Franco

**Comment by bminish** [comment]
Hi Franco,

Here's that output and I think you are on to something ;-) 

bminish@redbox:~/Radio/02-IQ-files-diversity$ time dual_tuner_recorder -r 8000000 -i 2048 -b 1536 -g AGC -l 1 -G -f 990000 -L -j 4000 -v -x 7200
SerNo=2403011F34 hwVer=3 tuner=0x03 rspDuoMode=0x02 rspDuoSampleFreq=8000000 internalDecimation=4
RX A - LO=990000 BW=1536 If=2048 Dec=1 IFagc=2 IFgain=50 LNAgain=1
RX A - DCenable=1 IQenable=1 dcCal=3 speedUp=0 trackTime=1 refreshRateTime=2048
RX B - LO=990000 BW=1536 If=2048 Dec=1 IFagc=2 IFgain=50 LNAgain=1
RX B - DCenable=1 IQenable=1 dcCal=3 speedUp=0 trackTime=1 refreshRateTime=2048
streaming for 7200 seconds
RX A - dropped 5764 samples
RX B - dropped 5764 samples
dropped 5764 samples - next_sample_num=133121604 first_sample_num=133127368
RX A - dropped 1073741824 samples
RX B - dropped 1073741824 samples
dropped 1073741824 samples - next_sample_num=1073741896 first_sample_num=72
RX A - dropped 1073741824 samples
RX B - dropped 1073741824 samples
dropped 1073741824 samples - next_sample_num=1073741832 first_sample_num=8
RX A - dropped 1073741824 samples
RX B - dropped 1073741824 samples
dropped 1073741824 samples - next_sample_num=1073742104 first_sample_num=280
RX A - dropped 26089 samples
RX B - dropped 26089 samples
dropped 26089 samples - next_sample_num=78312136 first_sample_num=78338225
RX A - dropped 16688 samples
RX B - dropped 16688 samples
dropped 16688 samples - next_sample_num=119287217 first_sample_num=119303905
RX A - dropped 33554 samples
RX B - dropped 33554 samples
dropped 33554 samples - next_sample_num=960604897 first_sample_num=960638451
RX A - dropped 2373 samples
RX B - dropped 2373 samples
dropped 2373 samples - next_sample_num=960686835 first_sample_num=960689208
RX A - dropped 1073741824 samples
RX B - dropped 1073741824 samples
dropped 1073741824 samples - next_sample_num=1073742120 first_sample_num=296
RX A - dropped 1073741824 samples
RX B - dropped 1073741824 samples
dropped 1073741824 samples - next_sample_num=1073742056 first_sample_num=232
RX A - dropped 1073741824 samples
RX B - dropped 1073741824 samples
dropped 1073741824 samples - next_sample_num=1073741992 first_sample_num=168
RX A - dropped 1073741824 samples
RX B - dropped 1073741824 samples
dropped 1073741824 samples - next_sample_num=1073741928 first_sample_num=104
RX A - dropped 1073741824 samples
RX B - dropped 1073741824 samples
dropped 1073741824 samples - next_sample_num=1073741864 first_sample_num=40
RX A - dropped 1073741824 samples
RX B - dropped 1073741824 samples
dropped 1073741824 samples - next_sample_num=1073742136 first_sample_num=312
RX A - dropped 1073741824 samples
RX B - dropped 1073741824 samples
dropped 1073741824 samples - next_sample_num=1073742072 first_sample_num=248
RX A - dropped 1073741824 samples
RX B - dropped 1073741824 samples
dropped 1073741824 samples - next_sample_num=1073742008 first_sample_num=184
RX A - dropped 1073741824 samples
RX B - dropped 1073741824 samples
dropped 1073741824 samples - next_sample_num=1073741944 first_sample_num=120
RX A - dropped 1073741824 samples
RX B - dropped 1073741824 samples
dropped 1073741824 samples - next_sample_num=1073741880 first_sample_num=56
total samples = 14399884800 / 14399884800
dropped samples = 13958728180 / 13958728180
elapsed time = 7199.913301 / 7199.913285
actual sample rate = 2000008 / 2000008
I samples range = [-18331,18588] / [-18642,19094]
Q samples range = [-19196,19363] / [-19353,19184]
samples per rx_callback range = [336,336] / [336,336]
output samples = 14399884800 (x2)
data size = 115199078400
blocks buffer usage = 384/4000
samples buffer usage = 258048/1048576
gain changes = 6 / 6

real    120m1.881s
user    7m42.811s
sys     17m0.195s

**Comment by fventuri** [comment]
I think I figured out the problem with those gaps in the sample sequence number that cause those very large 'dropped samples' false positives.

I also made a change in the code so that for small gaps in samples (less than 100,000 samples by default), the utility will fill that gap in the output file with a series of zeros. This way the number of values stored in the file should match exactly with the duration of the recording (and the phase of a signal before and after the gap should be correct). This value can be adjusted with the `-z` option; setting `-z 0` will make the utility just skip over any gap in the recorded file, as it does now.

Finally I added the option to write the output to stdout by setting the output file to just `-` (i.e. `-o -`). This could be useful in some cases; for instance if one wants to pipe the output through netcat/nc and send it to a remote computer; another use case could be compressing the output stream on the fly by piping it to 'gzip' or 'zstd'.
In this case the `-G` option to save a file for the gain changes is not supported.

If you want to give it a try, after `git pull`, you'll have to add back the line where you change the USB transfer mode to bulk, since I still haven't figured out why it doesn't work for me here. It is next in my list though.

Franco

**Comment by bminish** [comment]
Playing back a file recorded with the new version now and cannot say I noticed it playing though some zeros. This does seem like a very sensible solution to dealing with some dropped data.

I re-inserted my line for bulk transfer mode and all seems to be working well. Thank You for adding an option for sdtout, this opens up some intriguing possibilities in my use-case that I'll play with.

One other thing (& I am confident it has nothing to do with your software but may be an API artifact or hardware limitation) I have noticed is that all recordings made with -r 6000000 -i 1620 -b 1536 are offset in frequency terms by an absolute amount of + 0.48 Hz 
other ratios like -r 8000000 -i 2048 have a slightly different, but also positive offset. 
I'm using a GPDSO based reference to clock the RSPDuo and I wonder if this is connected in any way to what you noticed in relation to the runs of very large dropped samples and a possible API issue 

Brendan

**Comment by fventuri** [comment]
Brendan,
I do not have a GPSDO reference here, so I didn't notice the 480mHz offset.
If I were you, I would ask about it in the SDRplay users group: https://groups.io/g/SDRPlayUsers since there are a lot of very knowledgeable people there, and I would think someone else would have noticed it too.

Franco

**Comment by fventuri** [comment]
Also please disregard my comment earlier about bulk mode.

Tonight I had a better look at the code for `dual_tuner_recorder`, and I see it already has USB transfers set to bulk mode (https://github.com/fventuri/dual-tuner-recorder/blob/main/dual_tuner_recorder.c#L635), which means they have been working OK all along here.

Franco

**Comment by bminish** [comment]
Closing this 'issue' now as it's working perfectly in my application, many thanks Franco
